version: '3.8'

services:
  banking-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: banking-transaction-system:latest
    container_name: banking-transaction-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - banking-network

  # 可选：添加数据库服务（如果需要持久化H2数据库）
  # h2-database:
  #   image: oscarfonts/h2:latest
  #   container_name: h2-database
  #   ports:
  #     - "8082:1521"
  #     - "8083:81"
  #   environment:
  #     - H2_OPTIONS=-web -webAllowOthers -tcp -tcpAllowOthers -baseDir /opt/h2-data
  #   volumes:
  #     - h2-data:/opt/h2-data
  #   networks:
  #     - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  logs:
  # h2-data: 